name: Clot
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.2 
  ionicons: ^0.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#F4F4F4"
  color_dark: "#1D182A"
  image: "assets/images/splash.png"
  

  web: false

  android_12:
    color: "#F4F4F4"
    color_dark: "#1D182A"
    image: "assets/images/splash.png"
  
 