name: clot
description: An E-commerce shopping platform that provides a seamless and user-friendly experience for customers to browse, search, and purchase a wide range of products. With a modern and intuitive interface, advanced search capabilities, and personalized recommendations, our app aims to revolutionize the way people shop online. Whether you're looking for fashion, electronics, home decor, or any other category, our app has you covered. Start exploring and discover the joy of convenient and delightful online shopping!.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  ionicons: ^0.2.2
  shimmer: ^3.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.2 
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#F4F4F4"
  color_dark: "#1D182A"
  image: "assets/images/splash.png"
  

  web: false

  android_12:
    color: "#F4F4F4"
    color_dark: "#1D182A"
    image: "assets/images/splash.png"
  
 